// <auto-generated />
using System;
using ContabilizaJa.Movimentacao.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ContabilizaJa.Movimentacao.Data.Migrations
{
    [DbContext(typeof(MovimentacaoContext))]
    partial class MovimentacaoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("ContabilizaJa.Movimentacao.Domain.ExtratoBancario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DataFim");

                    b.Property<DateTime>("DataInicio");

                    b.Property<DateTime>("DataRegistro");

                    b.HasKey("Id");

                    b.ToTable("ExtratoBancario");
                });

            modelBuilder.Entity("ContabilizaJa.Movimentacao.Domain.Transacoes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Data");

                    b.Property<string>("Descricao");

                    b.Property<int?>("ExtratoId");

                    b.Property<string>("Tipo");

                    b.Property<decimal>("Valor");

                    b.HasKey("Id");

                    b.HasIndex("ExtratoId");

                    b.ToTable("Transacoes");
                });

            modelBuilder.Entity("ContabilizaJa.Movimentacao.Domain.Transacoes", b =>
                {
                    b.HasOne("ContabilizaJa.Movimentacao.Domain.ExtratoBancario", "Extrato")
                        .WithMany("Transacoes")
                        .HasForeignKey("ExtratoId");
                });
#pragma warning restore 612, 618
        }
    }
}
